#!/usr/bin/env bash

unset tmpdir
remove_tmpdir=no
if [[ -d /tmp ]]; then
  tmpdir="/tmp"
elif [[ ! -z ${TEMP+x} ]]; then
  tmpdir="$TEMP"
else
  remove_tmpdir=yes
  tmpdir=".tmp"
  mkdir -p ".tmp" || {
    echo "error: cannot create a temporary directory in the current directory."
    exit 1
  }
fi

if [[ ! -d "$tmpdir" ]]; then
  echo "error: invalid temporary directory from TEMP or TMPDIR variables"
  exit 1
fi

exit_cleanup () {
  if [[ $remove_tmpdir == yes && -d "$tmpdir" ]]; then
    rm -fr "$tmpdir"
  fi
  exit $1
}

pushd_quiet () { builtin pushd "$@" > /dev/null; }
popd_quiet () { builtin popd > /dev/null; }

prefix="$HOME/.local"

destdir="$prefix"
if [[ ":$PATH:" == *":$prefix/bin:"* ]]; then
  echo "Fine, $prefix/bin is in the PATH."
else
  echo "Warning: $prefix/bin is *not* in the PATH."
  need_path=true
fi

if [ ! -d "$destdir/bin" ]; then
  mkdir -p "$destdir/bin"
  if [ $? -ne 0 ]; then
    echo "Fatal error: Cannot create directory: $destdir/bin"
    echo "Aborting install"
    exit_cleanup 1
  fi
fi

pushd_quiet "$tmpdir"
echo -n "Downloading package from github... "
rm -fr lh-install
git clone --depth 1 https://github.com/franko/lhelper.git lh-install &> /dev/null
pushd_quiet lh-install
echo "done"

echo "Installing lhelper in directory $prefix... "
bash install "$destdir"

echo
echo "Lhelper successfully installed"
if [ ! -z ${need_path+set} ]; then
  echo "To use lhelper add the directory \"$destdir/bin\" to your PATH."
fi

popd_quiet
rm -fr lh-install
popd_quiet
exit_cleanup 0
