#!/usr/bin/env bash

LHELPER_PACKAGE_VERSION=1

recipes_branch=master
if [[ "$1" == "--use="* ]]; then
    recipes_branch="${1#--use=}"
    echo "Using recipes from branch: ${recipes_branch}"
    shift
fi

if [ $# != "1" ]; then
    echo "Usage: $0 <prefix>"
    exit 1
fi

pushd_quiet () { builtin pushd "$@" > /dev/null; }
popd_quiet () { builtin popd > /dev/null; }

have_command () {
    command -v "$1" &> /dev/null
}

find_compiler () {
    if [ -z ${CC+x} ]; then
        if have_command gcc; then
            echo gcc
        elif have_command clang; then
            echo clang
        else
            echo "error: cannot find a C compiler."
            echo "The variable CC is not set and neither gcc or clang are found."
            exit 1
        fi
    else
        echo "$CC"
    fi
}

lhcompile () {
    local exec_name="$1"
    if [[ "$OSTYPE" == "msys"* || "$OSTYPE" == "mingw"* || "$OSTYPE" == "cygwin"* ]]; then
        exec_name="${exec_name}.exe"
    fi
    local objs=()
    for src in "${@:2}"; do
        obj="${src/%.c/.o}"
        objs+=("$obj")
    done
    $lhcomp -c "$src" -o "$obj"
    $lhcomp -o $exec_name "${objs[@]}" && rm "${objs[@]}"
}

PREFIX="$1"

if [ -z "${DESTDIR+x}" ]; then
    DESTDIR="$PREFIX"
fi

recipes_repo="https://github.com/franko/lhelper-recipes.git"
recipes_dir="$DESTDIR/share/lhelper/recipes"

lhcomp="$(find_compiler)"

echo "Installing lhelper with prefix $DESTDIR"

mkdir -p "$DESTDIR/bin"
mkdir -p "$DESTDIR/share/lhelper/patch"
mkdir -p "$DESTDIR/var/lib/lhelper/builds"
mkdir -p "$DESTDIR/var/lib/lhelper/archives"
mkdir -p "$DESTDIR/var/lib/lhelper/packages/$LHELPER_PACKAGE_VERSION"
mkdir -p "$DESTDIR/var/lib/lhelper/digests"
mkdir -p "$DESTDIR/share/bash-completion/completions"

pushd_quiet src
for modname in path-replace sort cmp realpath; do
    echo "compiling lh-$modname"
    lhcompile lh-$modname lh-$modname.c
    if [ $? -ne 0 ]; then
        echo "error: cannot compile helper tool lh-$modname"
        exit 1
    fi
    cp lh-$modname "$DESTDIR/bin"
done
popd_quiet

cp build-helper.sh "$DESTDIR/share/lhelper"
cp create-env.sh "$DESTDIR/share/lhelper"
cp lhelper-bash-init "$DESTDIR/share/lhelper"
cp patch/*.patch "$DESTDIR/share/lhelper/patch"
cp lhelper "$DESTDIR/bin"

# warning: if DESTDIR is ~/.local, /usr, /usr/local the completion are going
# to work but for other prefix they may not work.
# Bash will use:
#   $HOME/.local/share/bash-completion/completions
#   $XDG_DATA_HOME/bash-completion/completions
#   $BASH_COMPLETION_USER_DIR/completions
if [[ $OSTYPE == "darwin"* ]]; then
    if command -v brew >/dev/null 2>&1; then
        cp lhelper-completion.bash "$(brew --prefix)/etc/bash_completion.d/lhelper"
    else
        echo "Warning: bash completion unsupported if Homebrew is not installed"
    fi
else
    cp lhelper-completion.bash "$DESTDIR/share/bash-completion/completions/lhelper"
fi

if [ -d "$recipes_dir" ]; then
	echo "Deleting existing recipes dir: $recipes_dir"
	rm -fr "$recipes_dir"
fi

chmod a+x "$DESTDIR/bin/lhelper"

echo -n "Installing recipes... "
if git clone --depth 1 -b "$recipes_branch" "$recipes_repo" "$recipes_dir" &> /dev/null; then
    echo "done"
else
    echo "fail"
    echo "Error cloning recipes from $recipes_repo"
    exit 1
fi
