#!/usr/bin/env bash

LHELPER_COMMAND_NAME=`basename $0`

if [ "$#" -lt 1 ]; then
    echo "Usage: $LHELPER_COMMAND_NAME <command> [<other options>]"
    exit 1
fi

LHELPER_BIN_DIRNAME="$(dirname $0)"
LHELPER_PREFIX="${LHELPER_BIN_DIRNAME%/bin}"

export LHELPER_WORKING_DIR="$LHELPER_PREFIX/var/lib/lhelper"
export LHELPER_DIR="$LHELPER_PREFIX/share/lhelper"

if [ ! -d "${LHELPER_DIR}" ]; then
    echo "error: directory "${LHELPER_DIR}" not found."
    echo "Lhelper may be not properly installed."
fi

build_env_digest () {
    source "$LHELPER_ENV_PREFIX/bin/lhelper-config"
    _digest=($(cat << EOF | md5sum
CC="$CC"
CXX="$CXX"
CFLAGS="$CFLAGS"
CXXFLAGS="$CXXFLAGS"
BUILD_TYPE="$BUILD_TYPE"
CC_VERSION="$($CC --version | head -n 1)"
CXX_VERSION="$($CXX --version | head -n 1)"
EOF
    ))
    echo "${_digest[0]}"
}

library_install () {
    if [ -z ${LHELPER_ENV_NAME+x} ]; then
        echo "error: no environment defined"
        exit 1
    fi

    if [ ! -f "$LHELPER_DIR/recipes/$1.sh" ]; then
        echo "error: recipe $1 does not exist."
        exit 1
    fi

    source "$LHELPER_DIR/build-helper.sh"
    export -f enter_git_repository enter_remote_archive inside_git_apply_patch inside_archive_apply_patch build_and_install install_pkgconfig_file interrupt_clean_archive install_library_with_command find_package_name build_env_digest library_dir_reloc prepare_temp_dir extract_archive_reloc

    export INSTALL_PREFIX="$LHELPER_ENV_PREFIX"
    if [[ "$OSTYPE" == "msys"* || "$OSTYPE" == "mingw"* ]]; then
        WIN_INSTALL_PREFIX="${INSTALL_PREFIX/#\/c\//c:\/}"
    else
        WIN_INSTALL_PREFIX="${INSTALL_PREFIX}"
    fi
    export WIN_INSTALL_PREFIX

    source "$LHELPER_ENV_PREFIX/bin/lhelper-config"

    local digest=$(build_env_digest)
    local tar_package_filename="$1-${digest}.tar.gz"
    if [ -f "$LHELPER_WORKING_DIR/packages/${tar_package_filename}" ]; then
        echo "PACKAGE EXISTS: ${tar_package_filename}"
    else
        echo "PACKAGE DO NOT EXISTS"
        echo "COMPILING..."
        bash -e "$LHELPER_DIR/recipes/$1.sh"
    fi
    echo "EXTRACTING..."
    extract_archive_reloc "${tar_package_filename}"
    echo "DONE"
}

start_subshell () {
    bash --init-file "$LHELPER_WORKING_DIR/environments/$1"
}

create_env () {
    bash "$LHELPER_DIR/create-env.sh" "$1" "$2"
}

case $1 in
install)
    if [ $# -lt 2 ]; then
        echo "Usage: $LHELPER_COMMAND_NAME install <library-name>"
        exit 1
    fi
    if [ -z ${LHELPER_ENV_NAME+x} ]; then
        echo "Please activate an environment before."
        exit 1
    fi
    library_install "$2"
    ;;
activate)
    if [ $# -lt 2 ]; then
        echo "Usage: $LHELPER_COMMAND_NAME activate <env-name>"
        exit 1
    fi
    start_subshell "$2"
    ;;
create)
    if [ $# -lt 2 ]; then
        echo "Usage: $LHELPER_COMMAND_NAME create <env-name> [env-root-dir]"
        exit 1
    fi
    create_env "$2" "$3"
    ;;
edit)
    if [ -z ${LHELPER_ENV_NAME+x} ]; then
        echo "Please activate an environment before."
        exit 1
    fi
    "${EDITOR-vim}" "$LHELPER_ENV_PREFIX/bin/lhelper-config"
    ;;
delete)
    if [ $# -lt 2 ]; then
        echo "Usage: $LHELPER_COMMAND_NAME delete <env-name>"
        exit 1
    fi
    _env_name="$2"
    if [ -f "$LHELPER_WORKING_DIR/environments/$_env_name" ]; then
        source "$LHELPER_WORKING_DIR/environments/$_env_name"
    else
        echo "Environment $_env_name not found."
        exit 1
    fi
    if [ -n "$LHELPER_ENV_PREFIX" ]; then
        echo -n "Are you sure you want to delete the environment $_env_name (y/n) ? "
        read _sure_delete
        if [[ "$_sure_delete" == "y" || "$_sure_delete" == "Y" ]]; then
            rm -fr "$LHELPER_ENV_PREFIX"
            rm -f "$LHELPER_WORKING_DIR/environments/$_env_name"
            echo "Environment $_env_name successfully deleted."
        else
            echo "Operation canceled."
        fi
        unset _sure_delete
    fi
    ;;
list)
    if [ "$2" == environments ]; then
        ls -1 "$LHELPER_WORKING_DIR/environments"
    elif [ "$2" == recipes ]; then
        ls -1 "$LHELPER_DIR/recipes" | sed 's/\.sh//'
    else
        echo "Usage: $LHELPER_COMMAND_NAME list (environments|recipes)"
        exit 1
    fi
    ;;
*)
    echo "error: unknown command $1"
    exit 1
    ;;
esac
